FROM maven:3-jdk-8

RUN apt-get -y update \
    && apt-get -y upgrade \
    && wget https://apertium.projectjj.com/apt/install-nightly.sh -O - | bash \
    && apt-get install -y apt-utils cg3 lsb-release python3 python3-pip \
    && python3 -m pip install gdown

RUN git clone https://github.com/reynoldsnlp/flair.git /opt/flair
WORKDIR /opt/flair

# add russian corenlp model
RUN mkdir src/main/webapp/WEB-INF/lib \
    && gdown https://drive.google.com/uc?id=1_0oU8BOiYCqHvItSsz0BjJnSNp8PRWlC \
       -O src/main/webapp/WEB-INF/lib/stanford-corenlp-russian-models-master-SNAPSHOT.jar \
    && mvn install:install-file \
       -Dfile=src/main/webapp/WEB-INF/lib/stanford-corenlp-russian-models-master-SNAPSHOT.jar \
       -DgroupId=edu.stanford.nlp \
       -DartifactId=stanford-corenlp-russian-models \
       -Dversion=master-SNAPSHOT \
       -Dpackaging=jar

# get all dependencies
RUN mvn -U dependency:resolve
